# Generated by Django 3.2.6 on 2023-07-25 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contadornotificaciones',
            name='mensaje',
            field=models.CharField(default='Mensaje predeterminado para esta acción', max_length=200),
        ),
    ]
