# Generated by Django 3.2.6 on 2022-08-11 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_auto_20220811_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='categories',
        ),
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Article', to='tienda.category', verbose_name='Categorias'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default=None, upload_to='articles', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='prueba',
            name='categories',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Categ', to='tienda.category', verbose_name='Categorias'),
        ),
    ]
