# Generated by Django 3.2.6 on 2023-07-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_contadornotificaciones_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contadornotificaciones',
            name='mensaje',
            field=models.CharField(choices=[('AGREGAR_AL_CARRITO', 'Se ha agregado un producto al carrito.'), ('ELIMINAR_DEL_CARRITO', 'Se ha eliminado un producto del carrito.'), ('ELIMINAR_UN_PRODUCTO', 'Se ha eliminado una unidad de un producto del carrito.')], default='AGREGAR_AL_CARRITO', max_length=200),
        ),
    ]
