# Generated by Django 3.2.6 on 2023-07-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_alter_contadornotificaciones_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contadornotificaciones',
            name='mensaje',
            field=models.CharField(default='Mensaje predeterminado para esta acción', max_length=200),
        ),
    ]
