# Generated by Django 3.2.6 on 2022-08-11 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tienda', '0004_auto_20220811_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prueba',
            name='categories',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Categ', to='tienda.category', verbose_name='CategoriasPrueba'),
        ),
        migrations.AlterField(
            model_name='prueba',
            name='content',
            field=models.CharField(max_length=150, verbose_name='ContenidoPrueba'),
        ),
        migrations.AlterField(
            model_name='prueba',
            name='image',
            field=models.ImageField(default=None, upload_to='articles', verbose_name='ImagenPrueba'),
        ),
        migrations.AlterField(
            model_name='prueba',
            name='title',
            field=models.CharField(max_length=150, verbose_name='TituloPrueba'),
        ),
        migrations.AlterField(
            model_name='prueba',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='UsuarioPrueba'),
        ),
    ]
