# Generated by Django 3.2.6 on 2023-07-27 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_alter_contadornotificaciones_mensaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contadornotificaciones',
            name='mensaje',
        ),
    ]
