# Generated by Django 3.2.6 on 2023-07-27 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_remove_contadornotificaciones_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='contadornotificaciones',
            name='mensaje',
            field=models.CharField(default='Mensaje predeterminado', max_length=200),
        ),
    ]
