# Generated by Django 3.2.6 on 2023-11-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_vendedorconfiguracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.CharField(max_length=1000, verbose_name='Contenido'),
        ),
    ]
