# Generated by Django 3.2.6 on 2023-03-18 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0009_productoindiv'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductoIndiv',
        ),
        migrations.AddField(
            model_name='article',
            name='contentcart',
            field=models.CharField(max_length=80, null=True, verbose_name='ContenidoCart'),
        ),
        migrations.AddField(
            model_name='article',
            name='titlecart',
            field=models.CharField(max_length=100, null=True, verbose_name='TituloCart'),
        ),
    ]
