# Generated by Django 5.0.7 on 2024-08-01 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0009_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='category_icons/', verbose_name='Icono'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mail_account',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mail'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='whatsapp_account',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Whatsapp'),
        ),
        migrations.AddField(
            model_name='vendedorconfiguracion',
            name='envio',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='paypal_account',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Paypal ID'),
        ),
    ]
