# Generated by Django 3.2.6 on 2023-03-18 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0008_productos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoIndiv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='Titulo')),
                ('content', models.CharField(max_length=80, null=True, verbose_name='Contenido')),
            ],
        ),
    ]
